### ISSUE TITLE
Illegal String Offset Error

### ISSUE THREAD

**Issue by claytoncollie** [WPBP/CPT_Columns#1]
I have been using this class for the past 6 months just fine and now I am seeing this error on the edit.php screen for my custom post type. The code still works perfectly when I only have one add_column called.  The problem lies in when I have more than one add_column for the class to loop through and build the array of columns.

called inside of a class
```
	public function register_columns(){

		$post_columns = new CPT_columns( $this->post_type );

                 $post_columns->add_column('hours',
			array(
				'label'    	=> __('Hours', $this->plugin_name),
				'type'     	=> 'post_meta',
				'meta_key' 	=> '_poa_office_hours', 
			)
		);

		$post_columns->add_column('map',
			array(
				'label'    	=> __('Map', $this->plugin_name),
				'type'     	=> 'custom_value',
				'meta_key'  => '_poa_office_map',
				'callback' 	=> array($this, 'get_the_map_url'), 
			)
		);
```

`Warning: Illegal string offset 'map' in /app/public/wp-content/plugins/power-of-attorney/vendor/wpbp/cpt_columns/CPT_Columns.php on line 159` 

`Warning: array_merge(): Argument #2 is not an array in /app/public/wp-content/plugins/power-of-attorney/vendor/wpbp/cpt_columns/CPT_Columns.php on line 166`

I have the post column code wrapped in a function that fires on admin-init.  I have the code working properly for SURE! I had it working and haven't change anything in relation to my column code.  I have all other plugins deactivated. I have just about everything else from my plugin disabled. I am at a total loss.

Problem seems to not be looping through all add_columns? not building the array properly? on line 159  then of course the array_merge fails for $tmp on line 166

**Comment by Mte90** [comment]
Bug confirmed, I am working on it!

**Comment by Mte90** [comment]
I released a new version so you have only to bump the version on your composer :-)
