### ISSUE TITLE
[Issue] Illegal offset type in isset 

### ISSUE THREAD

**Issue by rubendelblanco** [WPBP/CPT_Columns#3]
Hi, first of all congratulations for WPBP. It helps me a lot. I found and issue in CPT_Columns. My Settings page (made with CMB2 following the settings page demo from the boilerplate) throws me this error:
Uncaught TypeError: Illegal offset type in isset or empty in vendor\wpbp\cpt_columns\CPT_Columns.php:321

That's because $orderby = $query->get( 'orderby' ) returns me an associative array ["post_title"] => "ASC" I don't know why, because in settings page there isn't a CPT Column.

Anyway the issue fixes if you add the condition !is_array in line 321:
			if ( !is_array($orderby) && (!empty( $orderby ) && isset( $this->cpt_sortable_columns[ $orderby ], $this->cpt_sortable_columns[ $orderby ][ 'type' ]  )) && $this->cpt_sortable_columns[ $orderby ][ 'type' ] === 'custom_value' ) 

Should I post a Pull Request with the fix or do you have any other suggestion?

Greetings

**Comment by Mte90** [comment]
Thanks for reporting the issue and using WPBP.
If you have a fix for that just do a PR so I can check what was missing in the condition, as CPT Columns should be not executed in your settings page but on admin post type list.

**Comment by Mte90** [comment]
Thanks for reporting the issue and using WPBP.
If you have a fix for that just do a PR so I can check what was missing in the condition, as CPT Columns should be not executed in your settings page but on admin post type list.

**Comment by rubendelblanco** [comment]
Done. Check out https://github.com/WPBP/CPT_Columns/pull/4 
I don't know why that happens in the settings page. Maybe some other hook in my plugin forces that? Honestly, no clue.

**Comment by Mte90** [comment]
thanks for the PR, releasing a new version right now
